[[files]]
src = "mise-tasks/check/rust"
dest = ".mise/tasks/check/rust"

[[files]]
src = "mise-tasks/fmt/rust"
dest = ".mise/tasks/fmt/rust"

[[files]]
src = "mise-tasks/clean"
dest = ".mise/tasks/clean"

[[files]]
src = "cargo/config.toml"
dest = ".cargo/config.toml"
