owner = "milkyskies"
repo = "milky-kit"
project_number = 17
status_field_id = "PVTSSF_lAHOAGCvbs4BWoWCzhR67U8"
priority_field_id = "PVTSSF_lAHOAGCvbs4BWoWCzhR67Wc"
points_field_id = "PVTF_lAHOAGCvbs4BWoWCzhR67Wg"
